#ifndef CNOID_OPENRTMPYTHONPLUGIN_EXPORTDECL_H_INCLUDED
# define CNOID_OPENRTMPYTHONPLUGIN_EXPORTDECL_H_INCLUDED

# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_OPENRTMPYTHONPLUGIN_DLLIMPORT __declspec(dllimport)
#  define CNOID_OPENRTMPYTHONPLUGIN_DLLEXPORT __declspec(dllexport)
#  define CNOID_OPENRTMPYTHONPLUGIN_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_OPENRTMPYTHONPLUGIN_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_OPENRTMPYTHONPLUGIN_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_OPENRTMPYTHONPLUGIN_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_OPENRTMPYTHONPLUGIN_DLLIMPORT
#   define CNOID_OPENRTMPYTHONPLUGIN_DLLEXPORT
#   define CNOID_OPENRTMPYTHONPLUGIN_DLLLOCAL
#  endif
# endif

# ifdef CnoidOpenRTMPythonPlugin_STATIC
#  define CNOID_OPENRTMPYTHONPLUGIN_DLLAPI
#  define CNOID_OPENRTMPYTHONPLUGIN_LOCAL
# else
#  ifdef CnoidOpenRTMPythonPlugin_EXPORTS
#   define CNOID_OPENRTMPYTHONPLUGIN_DLLAPI CNOID_OPENRTMPYTHONPLUGIN_DLLEXPORT
#  else
#   define CNOID_OPENRTMPYTHONPLUGIN_DLLAPI CNOID_OPENRTMPYTHONPLUGIN_DLLIMPORT
#  endif
#  define CNOID_OPENRTMPYTHONPLUGIN_LOCAL CNOID_OPENRTMPYTHONPLUGIN_DLLLOCAL
# endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_OPENRTMPYTHONPLUGIN_DLLAPI
